#!/usr/bin/env ${PYTHON}

import sys
import xhtml
import time

def do_file(filename):

    fp = open(filename, "r")
    print "<!-- This file automatically generated by mirrorfmt.py $Revision$ -->"
    print xhtml.dl.init({"class" : "download-mirror"})

    for l in fp:
        l = l.rstrip()
        if len(l) > 1:
            if l[0] == "#":
                pass
            elif l[0] not in [' ', '\t', '\n']:
                print xhtml.dt(l)
            else:
                l = l.lstrip()
                print xhtml.dd(xhtml.hyperlink(l, {"href" : l}))
                pass
            pass
        pass

    print xhtml.dl.fini()

    return

def main(argv):
    for a in argv:
        do_file(a)
        pass
    
    return
 
main(sys.argv[1:])

