#!/usr/bin/env ${PYTHON}

import sys
import xhtml
import time
import string

def do_file(filename):

    fp = open(filename, "r")
    print "<!-- This file automatically generated by mirrorfmt.py $Revision$ -->"
    print xhtml.dl.init({"class" : "download-mirror"})

    for l in fp:
        l = l.rstrip()
        if len(l) > 1:
            if l[0] == "#":
                pass
            elif l[0] not in [' ', '\t', '\n']:
                print xhtml.dt(l)
            else:
                l = l.lstrip()
                idx = 0
                while idx < len(l) and l[idx] not in string.whitespace:
                    idx = idx + 1
                if idx < len(l):
                    # split the link (before whitespace) from the comment
                    print xhtml.dd(xhtml.hyperlink(l[0:idx], {"href" : l[0:idx]})
                                   + l[idx:len(l)])
                else:
                    print xhtml.dd(xhtml.hyperlink(l, {"href" : l}))
                pass
            pass
        pass

    print xhtml.dl.fini()
    fp.close()
    
    return

def main(argv):
    for a in argv:
        do_file(a)
        pass
    
    return
 
main(sys.argv[1:])

