<!-- -*- SGML -*- -->
 <td id="menu">
  <span>Site News</span>
  <div style="text-indent: 1em;"><a href="/news/news-index.cgi?news-pending">Pending News</a>
    <a href="/news/news-index.cgi?news-current">Current News</a>
    <a href="/news/news-index.cgi?news-archive">Archived News</a>
    <a href="/news/howto-news.html">HOWTO</a>
  </div>
  <span>Splash Contest</span>
  <div style="text-indent: 1em;"><a href="?contest-pending">Pending Entries</a>
    <a href="?contest-current">Current Entries</a>
    <a href="?contest-archive">Archived Entries</a>
  </div>
  <span>Administration</span>
  <div style="text-indent: 1em;"><a href="">Administrators</a>
  </div>
 </td>
 <td id="main">
