#!/bin/sh -x
#
# gimp-batch
#
# Copyright (C) 2002, 2003  Helvetix Victorinox, pseudonym
# 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA
#
echo "gimp-batch, Copyright 2003 Helvetix Victorinox, a pseudonym"
echo "gimp-batch comes with ABSOLUTELY NO WARRANTY."
echo "This is free software, and you are welcome to redistribute it under certain conditions"
script=$1
shift
cmds=`sed -e "s\\$1$1" -e "s\\$2$2" -e "s\\$3$3" -e "s\\$4$4" -e "s\\$5$5" -e "s\\$6$6" -e "s\\$7$7" -e "s\\$8$8" -e "s\\$9$9" ${script}`
gimp -i -c -d -s -b "${cmds}"
