#!/usr/bin/perl -w

# The GIMP -- an image manipulation program
# Copyright (C) 2000 Sven Neumann <sven@gimp.org>

# web page generation by Nathan Summers <rock@gimp.org>

# No, this script does not create new GIMP authors ;-)


my $contributors = {};

 
print "\nProcessing contributors...\n";

open (INPUT, "contributors")
    or die ("Couldn't open file 'contributors'.");
while (<INPUT>) 
{
    chomp;    
    s/[,\.]$//;
    if (length ($_) and not (/^\#/))
    {
	if (/(.{1,})\[(.{1,})\]/)
	{
	    $utf{$1} = $2;
	    push (@contributors, $1);
	}
	else 
	{
	    push (@contributors, $_);
	}
    }
}
close (INPUT);


open (AUTHORS, ">authors.html")
    or die ("Couldn't write to file 'authors.html'.");
print AUTHORS <<EOT;
<!--#include virtual="/includes/header_pretitle.inc" -->
<title>GIMP - Authors</title>
<!--#include virtual="/includes/header_posttitle.inc" -->
<!--#include virtual="/includes/menu.inc" -->
<!-- NOTE: This file is autogenerated by authorsgen.pl. -->

<div class="heading">Authors: The people that made it happen!</div>

<div class="subtitle">Main Authors</div>
<ul>
<li>Spencer Kimball</li>
<li>Peter Mattis</li>
</ul>

<div class="subtitle">Contributers</div>

With patches, fixes, plugins, extensions, scripts, translations, documentation,
and more from (in alphabetical order):
<ul>
EOT

foreach $author (@contributors)
{   
    if ($utf{$author})
    {
	print AUTHORS "<li>$utf{$author}</li>\n";
    }
    else
    {
	print AUTHORS "<li>$author</li>\n";
    }
}

print AUTHORS <<EOT;
</ul>

<!-- it would really be cool if we could have links to the homepages of the
     authors or other information about the contributions that they have
     made. But at least this is a start. -- Rockwalrus -->

<!--#include virtual="/includes/linkbar.inc" -->
<!--#include virtual="/includes/footer.inc" -->
EOT

close (AUTHORS);

exit;
