<?xml version="1.0" encoding="UTF-8"?>

<!--  simple XSL transformation to create authors.htrw from authors.xml  -->

<xsl:stylesheet version="1.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:dc="http://purl.org/dc/elements/1.1/">

<!--
      FIXME: This code is ugly and uses &lt; and &gt; instead of using
             xsl:element and xsl:comment in the right way.  But it works...
-->

  <xsl:output method="text" />

  <xsl:template name="recent-contributor">
    <xsl:param name="role" />
    <xsl:apply-templates select="dc:contributor[contains(@role, $role) and number(@last-active) >= 2.4]" />
  </xsl:template>

  <xsl:template name="former-contributor">
    <xsl:param name="role" />
    <xsl:apply-templates select="dc:contributor[contains(@role, $role) and number(@last-active) &lt; 2.4]" />
  </xsl:template>

  <xsl:template match="/dc:gimp-authors">
    <xsl:text>&lt;!--#include virtual="/includes/wgo-xhtml-init.xhtml" --&gt;
&lt;title&gt;GIMP - Authors&lt;/title&gt;
&lt;!--#include virtual="/includes/wgo-look-feel.xhtml" --&gt;
&lt;!--#include virtual="/includes/wgo-page-init.xhtml" --&gt;

&lt;!--
   THIS FILE IS AUTOGENERATED - DO NOT EDIT!

   You can edit the source files authors.xml and authors.xsl instead.
   Check the Makefile for details.
--&gt;

&lt;h1&gt;Authors: The people that made it happen!&lt;/h1&gt;

&lt;h2&gt;Original authors&lt;/h2&gt;
&lt;ul&gt;
</xsl:text>
    <xsl:apply-templates select="dc:creator" />
    <xsl:text>&lt;/ul&gt;

&lt;h2&gt;Current developers&lt;/h2&gt;
&lt;p&gt;Contributing patches, fixes, plugins, extensions, scripts and other
  &lt;a href="wgo:develop"&gt;improvements to the code&lt;/a&gt; for GIMP 2.4.&lt;/p&gt;
&lt;ul&gt;
</xsl:text>
    <xsl:call-template name="recent-contributor">
      <xsl:with-param name="role" select="'author'"/>
    </xsl:call-template>
    <xsl:text>&lt;/ul&gt;

&lt;h2&gt;Artists&lt;/h2&gt;
&lt;p&gt;Contributing icons, cursors, brushes, gradients, patterns, etc.&lt;/p&gt;
&lt;ul&gt;
</xsl:text>
    <xsl:call-template name="recent-contributor">
      <xsl:with-param name="role" select="'artist'"/>
    </xsl:call-template>
    <xsl:text>&lt;/ul&gt;

&lt;h2&gt;Documenters&lt;/h2&gt;
&lt;p&gt;Contributing &lt;a href="wgo:docs"&gt;documentation&lt;/a&gt;&lt;/p&gt;
&lt;ul&gt;
</xsl:text>
    <xsl:call-template name="recent-contributor">
      <xsl:with-param name="role" select="'documenter'"/>
    </xsl:call-template>
  <xsl:text>&lt;/ul&gt;

&lt;h2&gt;Former contributors&lt;/h2&gt;
&lt;p&gt;People who contributed code, art or documentation to older
    GIMP releases.&lt;/p&gt;
&lt;ul&gt;
</xsl:text>
    <xsl:call-template name="former-contributor" />
    <xsl:text>&lt;/ul&gt;

&lt;!--#include virtual="/includes/wgo-page-fini.xhtml" --&gt;
&lt;!--#include virtual="/includes/wgo-xhtml-fini.xhtml" --&gt;

</xsl:text>
  </xsl:template>

  <xsl:template match="dc:creator">
    <xsl:text>  &lt;li&gt;</xsl:text><xsl:apply-templates /><xsl:text>&lt;/li&gt;
</xsl:text>
  </xsl:template>

  <xsl:template match="dc:contributor">
    <xsl:text>  &lt;li&gt;</xsl:text><xsl:apply-templates /><xsl:text>&lt;/li&gt;
</xsl:text>
  </xsl:template>

</xsl:stylesheet>
