#!/bin/sh

#replace /usr/local with the path to your GIMP build

prefix="/usr/local"


ACLOCAL_FLAGS="-I $prefix/share/aclocal"
export ACLOCAL_FLAGS
echo "ACLOCAL_FLAGS set to $ACLOCAL_FLAGS"
PKG_CONFIG_PATH="$prefix/lib/pkgconfig:$PKG_CONFIG_PATH"
export PKG_CONFIG_PATH
echo "PKG_CONFIG_PATH set to $PKG_CONFIG_PATH"

if [ $prefix != "/usr/local" ]; then
    PATH="$prefix/bin:$PATH"
    export PATH
    echo "PATH set to $PATH"
    LD_LIBRARY_PATH="$prefix/lib:$LD_LIBRARY_PATH"
    export LD_LIBRARY_PATH
    echo "LD_LIBRARY_PATH set to $LD_LIBRARY_PATH"
fi

echo "You can now build GIMP in $prefix."
