#!/bin/sh

cd /home/wgo/var/spool


/usr/bin/cvs -d :pserver:anonymous@anoncvs.gnome.org:/cvs/gnome checkout gegl/ChangeLog
/usr/bin/head -100 gegl/ChangeLog > /home/wgo/about/ChangeLogs/ChangeLog-gegl-unstable.txt
/bin/rm -rf gegl/
