#!/bin/sh -x

cd /home/wgo/var/spool

/usr/bin/cvs -d :pserver:anonymous@anoncvs.gimp.org:/cvs/gnome checkout gimp/ChangeLog

/usr/bin/head -100 gimp/ChangeLog > /home/wgo/about/ChangeLogs/ChangeLog-gimp-unstable.txt
/bin/rm -rf gimp/
