<!-- -*- SGML -*- -->
 <td id="menu">
  <span>www.gimp.org</span>
  <div style="text-indent: 1em;"><a href="/index.html">Home</a>
    <a href="/contest">Contest</a>
  </div>
  <span>Site Administration</span>
  <div style="text-indent: 1em;"><a href="/admin/index.html">Main Admin</a>
    <a href="/admin/howto.html">HOWTO</a>
  </div>
  <span>News</span>
  <div style="text-indent: 1em;"><a href="/admin/news/news-index.cgi?news-pending">Pending News</a>
    <a href="/admin/news/news-index.cgi?news-current">Current News</a>
    <a href="/admin/news/news-index.cgi?news-archive">Archived News</a>
    <a href="/admin/news/howto-news.html">HOWTO</a>
  </div>
  <span>Contest(s)</span>
  <div style="text-indent: 1em;"><a href="/admin/contest/gallery-edit.cgi">Splash Contest</a>
  </div>
 </td>
 <td id="main">
