<!-- -*- SGML -*- -->
 <td id="menu">
  <span>www.gimp.org</span>
  <div>
    <a href="/index.html">Home</a><br />
    <a href="/contest">Contest</a><br />
  </div>
  <span>Site Administration</span>
  <div>
    <a href="/admin/index.html">Main Admin</a><br />
    <a href="/admin/howto.html">HOWTO</a><br />
  </div>
  <span>News</span>
  <div>
    <a href="/admin/news/news-index.cgi?news-pending">Pending News</a><br />
    <a href="/admin/news/news-index.cgi?news-current">Current News</a><br />
    <a href="/admin/news/news-index.cgi?news-archive">Archived News</a><br />
    <a href="/admin/news/howto-news.html">HOWTO</a><br />
  </div>
  <span>Contest(s)</span>
  <div><a href="/admin/contest/gallery-edit.cgi">Splash Contest</a><br />
  </div>
 </td>
 <td id="main">
