<!-- -*- sgml -*- -->
<tr><td></td><td></td><td></td><td style="text-align: right;">
    <table class="ld" cellpadding="0" cellspacing="0" width="100%"><tbody>
        <tr class="ld"><td class="l--x--">&emsp;</td><td class="l-----">&emsp;</td></tr><tr class="ld"><td class="l--x--">&emsp;</td><td class="l-----">&emsp;</td></tr></tbody></table></td></tr>
<tr><td></td><td></td><td style="text-align: right;">

    <input class="submit-button" type="submit" name="action" value="delete" />
    <input class="submit-button" type="submit" name="action" value="pending" />
    <input class="submit-button" type="submit" name="action" value="archive" />
    <input type="hidden" name="queue" value="current" />
  </td><td>
    <table class="ld" cellpadding="0" cellspacing="0" width="100%"><tbody>
        <tr class="ld"><td class="l--xx-">&emsp;</td><td class="l-----">&emsp;</td></tr><tr class="ld"><td class="l-----">&emsp;</td><td class="l-----">&emsp;</td></tr></tbody></table></td>
</tr>
</tbody>
</table>
</form>
