<!-- -*- sgml -*- -->
<tr>
  <td></td>
  <td></td>
  <td></td>
  <td style="text-align: right;">
    <table class="ld" cellpadding="0" cellspacing="0" border="0"><tbody>
        <tr class="ld"><td class="l--x--">&emsp;</td><td class="l----x">&emsp;</td></tr>
        <tr class="ld"><td class="l--x--">&emsp;</td><td class="l----x">&emsp;</td></tr>
      </tbody></table>
  </td>
</tr>
<tr>
  <td></td>
  <td></td>
  <td style="text-align: right;">
    <input class="submit-button" type="submit" name="action" value="delete" />
    <input class="submit-button" type="submit" name="action" value="approve" />
    <input type="hidden" name="queue" value="pending" />
    <span style="padding: 2px;"></span>
  </td>
  <td style="margin: 0; padding: 0;">
    <table class="ld" cellpadding="0" cellspacing="0" border="0"><tbody>
        <tr><td class="l--xx-">&emsp;</td><td class="l----x">&emsp;</td></tr>
        <tr><td class="l-x---">&emsp;</td><td class="l-----">&emsp;</td></tr>
      </tbody></table>
  </td>
</tr>
</tbody>
</table>
</form>
