<div class="heading"><span class="title">About GIMP</span><span class="date"></span>&nbsp;</div>
<div class="item">
  <p>
    GIMP is an acronym for GNU Image Manipulation Program. It
    is a freely distributed piece of software suitable for such tasks
    as photo retouching, image composition and image authoring.
  </p>
  <p>
    It is an extremely capable piece of software with many capabilities. It 
    can be used as a simple paint program, a expert quality photo retouching 
    program, an online batch processing system, a mass production image 
    renderer, a image format converter, etc.
  </p>  
  <p>
    GIMP is extremely expandedable and extensible. It is designed to be 
    augmented with plugins and extensions to do just about anything. The 
    advanced scripting interface allows everything from the simplest task to 
    the most complex image manipulation procedures to be easily scripted. 
  </p>  
  <p>
    GIMP is written and developed under X11 on UNIX platforms.
    There is an <a href="http://www.netlabs.org/gimp/">OS/2 port</a> in development. 
    There is also a native win32 port available at <a href="http://www.gimp.org/win32/">Tor Lillqvist's</a>
    site. And some people have reported success in getting GIMP to run in
    <a href="http://www.macgimp.org/">MacOS X</a>.
  </p>
</div>

<div class="heading"><span class="title">Features and Capabilities</span><span class="date"></span>&nbsp;</div>
<div class="item">
  <p>
    This is only a very quickly thrown together list of GIMP features. This is only the tip of the iceberg.
    <ul>
      <li> Full suite of painting tools including Brush, Pencil, Airbrush, Clone,etc.
      <li> Tile based memory managent so image size is limited only by available disk space.
      <li> Sub-pixel sampling for all paint tools for high quality anti-aliasing
      <li> Full alpha channel support
      <li> Layers and channels
      <li> A Procedural Database for calling internal GIMP functions from external programs as in Script-fu
      <li> Advanced scripting capabilities
      <li> Multiple Undo/Redo (limited only by diskspace)
      <li> Virtually unlimited number of images open at one time
      <li> Extremely powerful gradient editor and blend tool.
      <li> Load and save animations in a convenient frame-as-layer format.
      <li> Transformation tools including rotate, scale, shear and flip.
      <li> File formats supported include gif, jpg, png, xpm, tiff, tga, mpeg, ps, pdf, pcx, bmp, and many others.
      <li> Load, display, convert, save to many file formats.
      <li> Selection tools including rectangle, ellipse, free, fuzzy, bezier and intelligent.
      <li> Plug-ins which allow for the easy addition of new file formats and new effect filters.
      <li> Over 100 plugins already available.
      <li> Supports custom brushes and patterns
      <li> Much, much more!
    </ul>
  </p>
</div>

