<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
  <head>
    <title>GIMP - The GNU Image Manipulation Program</title>
    <link rel="stylesheet" type="text/css" href="/style/default.css"/>
  </head>

  <body>

    <div id="titlebar"><a href="http://www.gimp.org"><img id="titlebarleft" src="/images/thegimp.png" alt=""/></a><img id="titlebarright" src="/images/wilberright.png" alt=""/></div>

    <table id="layout">
      <tr>
