        </td>        
      </tr>
    </table>

    <div id="linkbar">
      <span class="linkitem"><a href="links.html">GIMP Links</a></span>
      <span class="linkitem"><a href="http://gug.sunsite.dk">GIMP User Group</a></span>
      <span class="linkitem"><a href="http://gimp-savvy.com/BOOK/index.html">Grokking the GIMP</a></span>
      <span class="linkitem"><a href="FIXME">Mailing Lists</a></span>
      <span class="linkitem"><a href="FIXME">FAQ's</a></span>
      <span class="linkitem"><a href="FIXME">GIMP Books</a></span>
    </div>
