        <td id="menu">
          <a href="/index.html">News</a><br/>
          <a href="/about">About GIMP</a><br/>
          <a href="/resources.html">Resources</a><br/>
          <a href="/registry.html">Plug-In Registry</a><br/>
          <a href="/documentation.html">Documentation</a><br/>
          <a href="/tutorials">Tutorials</a><br/>
          <a href="/authoring.html">Script Authoring</a><br/>
          <a href="/development.html">Development</a><br/>
          <br/>
          <a href="/unix">GIMP for Unix</a><br/>
          <a href="/windows">GIMP for Windows</a><br/>
          <a href="/macintosh.html">GIMP for Macintosh</a><br/>
          <a href="/os2.html">GIMP for OS/2</a><br/>
          <br/>
          Newest Plug-Ins:<br/>
          <a href="FIXME">Gaussian blur * (1.0)</a><br/>
          <a href="FIXME">PSD Import/Export (2.7)</a><br/>
          <br/>
          <br/>
        </td>

        <td id="main">
