        <td id="menu">
          <a href="/index.html">News</a><br/>
          <a href="/about/">About GIMP</a><br/>
          <a href="/resources/">Resources</a><br/>
          <a href="/registry.html">Plug-In Registry</a><br/>
          <a href="/docs/">Documentation</a><br/>
          <a href="/tutorials/">Tutorials</a><br/>
          <a href="/bugzilla.html">Bugs</a><br/>
          <a href="/develop/">Development</a><br/>
          <br/>
          <a href="/unix/">GIMP for Unix</a><br/>
          <a href="/windows/">GIMP for Windows</a><br/>
          <a href="/unix/">GIMP for Macintosh</a><br/>
          <a href="/os2/">GIMP for OS/2</a><br/>
          <br/>
          <br/>
        </td>

        <td id="main">
