<h1><span class="newstitle">This is the second news item</span><span class="newsdate">2099-01-01</span></h1>
<p class="news">
  <img src="images/nicefolder.png" alt="" class="icon" />
  This is a test of a news item for www.gimp.org.  It will soon be replaced by
  real news.
</p>
<h1><span class="newstitle">This is the first news item</span><span class="newsdate">2098-12-31</span></h1>
<p class="news">
  <img src="images/nicefolder.png" alt="" class="icon" />
  Congratulations, your copy of the GIMP web site is up and running.
</p>
