<div class="newsheading"><span class="newstitle">Yet Another News Item</span><span class="newsdate">2002-09-20</span>&nbsp;</div>
<p class="news">
  <img src="images/nicefolder.png" alt="" class="icon"/>
  Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, 
  Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, 
  Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, 
  Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, 
  Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, 
  Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, 
  Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, 
  Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item, Another news item
</p>
<div class="newsheading"><span class="newstitle">Hello World</span><span class="newsdate">2002-09-17</span>&nbsp;</div>
<p class="news">
  <img src="images/nicefolder.png" alt="" class="icon"/>
  Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, 
  Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, 
  Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, 
  Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item.
</p>
<p class="news"> 
  Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, 
  Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, 
  Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item, Some boring news item.
</p>
