<p>
  <a href="http://bugs.gimp.org">bugs.gimp.org</a><br />
  <a href="http://bugzilla.gnome.org">bugzilla.gnome.org</a><br />
  Take your bugs here.
</p>
<p>
  <a href="http://developer.gimp.org">developer.gimp.org</a><br />
  GIMP Developer site
</p>
<p>
  <a href="http://gui.gimp.org" title="GIMP Usability">gui.gimp.org</a><br />
  GIMP UI Redesign Wiki
</p>
<p>
  <a href="http://docs.gimp.org">docs.gimp.org</a><br />
  GIMP Documentation
</p>
<p>
  <a href="http://registry.gimp.org">registry.gimp.org</a><br />
  Plug-ins &amp; Scripts
</p>
