<!-- -*- xml -*- -->
<h2>Mail List URLs</h2>
<p>
  <a href="http://lists.xcf.berkeley.edu/mailman/listinfo/gimp-user">GIMP User</a><br />
  The original (mostly linux based) user list.
</p>
<p>
  <a href="http://groups.yahoo.com/group/gimpwin-users/">GIMPwin-users</a><br />
  especially for users of the Windows-version of GIMP
</p>
<p>
  <a href="http://lists.xcf.berkeley.edu/mailman/listinfo/gimp-developer">GIMP Developer</a><br />
  The GIMP developer mail list.
</p>
<p>
  <a href="http://groups.yahoo.com/group/gimpi/">GIMPImages</a><br />
   GIMPI is a group dedicated to exchange of images created or manipulated with GIMP.
</p>
