<h2>Important GIMP Links</h2>
  <ul>
    <li><a href="http://www.gimp.org">The GNU Image Manipulation Program</a></li>
    <li><a href="http://wiki.gimp.org/">GIMP Wiki</a></li>
    <li><a href="home:gimp-bugzilla-stable">GIMP Bugzilla</a></li>
    <li><a href="home:gtk">The GIMP Tool Kit</a></li>
    <li><a href="wgo:license">GNU General Public License</a></li>
    <li><a href="home:gnu">GNU Project</a></li>
  </ul>
<h2>GIMP Planets</h2>
  <ul>
    <li><a href="http://paths.gimp.org">GNU Art News</a></li>
    <li><a href="http://parasites.gimp.org">GIMP Active Bugs</a></li>
    <li><a href="http://layers.gimp.org">GIMP Developer Web Logs</a></li>
    <li><a href="http://pixels.gimp.org">GIMP User Web Logs</a></li>
    <li><a href="http://undo.gimp.org">Release News</a></li>
  </ul>
