<h2>Important GIMP Links</h2>
  <ul>
    <li><a href="http://www.gimp.org/">The GNU Image Manipulation Program</a> - www.gimp.org</li>
    <li><a href="http://wiki.gimp.org/">GIMP Wiki</a> - wiki.gimp.org</li>
    <li><a href="http://bugs.gimp.org/">GIMP Bugzilla</a> - bugs.gimp.org</li>
    <li><a href="http://www.gtk.org/">The GIMP Tool Kit</a> - www.gtk.org</li>
    <li><a href="http://www.gnu.org/">GNU Project</a> - www.gnu.org</li>
    <li><a href="/about/COPYING">GNU General Public License</a> - GPL</li>
  </ul>

<h2>GIMP RSS feeds</h2>
  <ul>
    <li><a href="https://bugzilla.gnome.org/buglist.cgi?bug_file_loc_type=substring&bug_status=UNCONFIRMED&bug_status=NEW&bug_status=ASSIGNED&bug_status=NEEDINFO&bug_status=REOPENED&bug_status=RESOLVED&bug_status=VERIFIED&bug_status=CLOSED&changedin=7&chfieldto=Now&product=GIMP&query_format=advanced&title=Bug%20List:%20GIMP%20-%20Current%20Bug%20Week&ctype=atom">GIMP Active Bugs</a></li>
  </ul>
