<h2>Important GIMP Development Links</h2>
<p>
  <a href="http://developer.gimp.org">GIMP developers</a><br />
  The main GIMP development website.
</p>
<p>
  <a href="http://www.gegl.org/">GEGL --GIMP 'E' Graphical Library</a><br />
  An image processing library based on GObjects.
</p>
<p>
  <a href="http://cvs.gnome.org/bonsai/">GNOME Bonsai</a><br />
  Perform queries on the contents of the CVS archive.
</p>
