<h2><a name="development"></a>GIMP Development Links</h2>
<p>
  <a href="http://developer.gimp.org">GIMP developers</a><br />
  The main GIMP development website.
</p>
<p>
  <a href="http://edhel.gimp.org/devnews.html">GIMP Development News</a><br />
  What happens in GIMP development, updated regularily.
</p>
<p>
  <a href="http://www.gegl.org/">GEGL</a><br />
  An image processing library based on GObjects.
</p>
<p>
  <a href="http://cvs.gnome.org/">GNOME CVS</a><br />
  GNOME CVS source code repository
</p>
