<a name="maillists">
<div class="subtitle">Mail List URLs</div>
<p>
  <A href="maillists.html">Mail List Descriptions</a><br />
  A more thorough overview of The GIMP related mail lists.
</p>
<p>
  <A href="http://lists.xcf.berkeley.edu/mailman/listinfo/gimp-user">GIMP User</a><br>
  The original (mostly linux based) user list.
</p>
<p>
  <A href="http://groups.yahoo.com/group/gimpwin-users/">GIMPwin-users</a><br />
  especially for users of the Windows-version of GIMP
</p>
<p>
  <A href="http://lists.xcf.berkeley.edu/mailman/listinfo/gimp-developer">GIMP Developer</a><br>
  The GIMP developer mail list.
</p>
<p>
  <A href="http://groups.yahoo.com/group/gimpwin-dev/">GIMPwin-dev</a><br />
  for anyone who is interested in developing for the Windows-version of GIMP
</p>
<p>
  <A href="http://groups.yahoo.com/group/gimpi/">GIMPImages</a><br />
  need to get something from their FAQ for here.
</p>
