<p>
  <A href="http://www.gimp.org">www.gimp.org</a><br />
  <A href="http:// i.just.love.the.gimp.org"> i.just.love.the.gimp.org</a><br />
  <A href="http:// bring.out.the.gimp.org"> bring.out.the.gimp.org</a><br />
  The GIMP web site.
</p>
<p>
  <A href="http://bugs.gimp.org">bugs.gimp.org</a><br />
  <A href="http://bugzilla.gimp.org">bugzilla.gimp.org</a><br />
  Take your bugs here.
</p>
<p>
  <A href="http://developer.gimp.org">developer.gimp.org</a><br />
  The GIMP Developer site
</p>
<p>
  <A href="http://manual.gimp.org">manual.gimp.org</a><br />
  The GIMP User Maunual (GUM)
</p>
<p>
  <A href="http://registry.gimp.org">registry.gimp.org</a><br />
  Plug-ins.
</p>
<p>
  <A href="http://ircd.gimp.org">ircd.gimp.org</a><br />
  The Official site of GIMPNet.
</p>
