<h2>Important GIMP Links</h2>
  <ul>
    <li><a href="http://www.gimp.org">The GNU Image Manipulation Program</a></li>
    <li><a href="http://www.gnu.org/">GNU Project</a></li>
    <li><a href="http://bugs.gimp.org/">GIMP Bugzilla</a></li>
    <li><a href="http://www.gtk.org/">The Gimp Tool Kit</a></li>
    <li><a href="http://www.google.com/">Google</a></li>
  </ul>
<h2>GIMP Planets</h2>
  <ul>
    <li><a href="http://paths.gimp.org">GNU Art News</a></li>
    <li><a href="http://parasites.gimp.org">GIMP Active Bugs</a></li>
    <li><a href="http://layers.gimp.org">GIMP Developer Web Logs</a></li>
    <li><a href="http://pixels.gimp.org">GIMP User Web Logs</a></li>
    <li><a href="http://undo.gimp.org">Release News</a></li>
  </ul>
