<p>
  <a href="http://bugs.gimp.org">bugs.gimp.org</a><br />
  <a href="http://bugzilla.gimp.org">bugzilla.gimp.org</a><br />
  Take your bugs here.
</p>
<p>
  <a href="http://developer.gimp.org">developer.gimp.org</a><br />
  The GIMP Developer site
</p>
<p>
  <a href="http://gui.gimp.org" title="GIMP Usability">gui.gimp.org</a><br />
  GIMP UI Redesign Wiki
</p>
<p>
  <a href="http://manual.gimp.org">manual.gimp.org</a><br />
  The GIMP User Maunual (GUM)
</p>
<p>
  <a href="http://registry.gimp.org">registry.gimp.org</a><br />
  Plug-ins.
</p>
<p>
  <a href="http://ircd.gimp.org">ircd.gimp.org</a><br />
  The Official site of GIMPNet.
</p>
