#!/usr/bin/env ${PYTHON}
# -*- mode: python py-indent-offset: 2; -*-
#
# www.gimp.org website administration and tools
#
# Copyright (C) 2002, 2003 Helvetix Victorinox, a pseudonym,
# Mountain View, California
# 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA

import string
import os

import xhtml
import wgo_config as config

import apache_ssi


def spool_file(name, suffix=""):
  return (config.spool_dir + os.path.basename(name) + suffix)


def spool_path(name, suffix=""):
  return (config.spool_path + os.path.basename(name) + suffix)


def error(text):
  return (xhtml.h2("Eeek! An error!", {"class" : "subtitle"}) + xhtml.para(text))

def http_preamble(headers=[]):
  print string.join(headers, "\n")
  print
  return
  
#
# This is highly dependent upon the layout in the include files, which
# makes this messy. XXX
#
def header(format="page", title="", links=None):

  print xhtml_init()
  
  print xhtml.title(title)
  print look_feel()

  print xhtml.link({"rel" : "stylesheet",
                    "href" : "/style/extended.css",
                    "type" : "text/css",
                    "title" : title})

  for link in links:
    print xhtml.link(link)
    pass
  
  print page_init(format)

  return (True)


def footer(prefix=None):
  if prefix != None:
    print prefix
    pass
  
  print page_fini()                     # XXX need to communicate the page format here.
  print xhtml_fini()
  

  #"data" : 'data:base64, ' + xhtml.encodefile('/home/asdf/public_html/helvetix/anybrowser.png')})
  #                                      "data" : 'data:binary, ' + xhtml.include('/home/asdf/public_html/helvetix/anybrowser.png')})

  return (True)


def xhtml_init():
  ssi = apache_ssi.processor()
  ssi.document_root = config.DocumentRoot_path
  s = ssi.parse(config.DocumentRoot_path + '/includes/wgo-xhtml-init.xhtml')
  s += xhtml.comment("This document was automatically generated by wgo.py $Revision$ and friends.")
  return (s)


def xhtml_fini():
  ssi = apache_ssi.processor()
  ssi.document_root = config.DocumentRoot_path
  s = ssi.parse(config.DocumentRoot_path + '/includes/wgo-xhtml-fini.xhtml')
  return (s)


def look_feel():
  ssi = apache_ssi.processor()
  ssi.document_root = config.DocumentRoot_path
  s = ssi.parse(config.DocumentRoot_path + '/includes/wgo-look-feel.xhtml')
  return (s)


def page_init(format="page"):
  ssi = apache_ssi.processor()
  ssi.document_root = config.DocumentRoot_path
  s = ssi.parse(config.DocumentRoot_path + '/includes/wgo-' + format + '-init.xhtml')
  return (s)


def page_fini(format="page"):
  ssi = apache_ssi.processor()
  ssi.document_root = config.DocumentRoot_path
  s = ssi.parse(config.DocumentRoot_path + '/includes/wgo-' + format + '-fini.xhtml')
  return (s)
