#!/usr/bin/env ${PYTHON}
# -*- mode: python py-indent-offset: 2; -*-
#
# www.gimp.org website administration and tools
#
# Copyright (C) 2002, 2003 Helvetix Victorinox, a pseudonym,
# Mountain View, California
# 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA

import xhtml
import wgo_config as config
import os


def spool_file(name, suffix=""):
  return (config.spool_dir + os.path.basename(name) + suffix)


def spool_path(name, suffix=""):
  return (config.spool_path + os.path.basename(name) + suffix)


def error(text):
  return (xhtml.div("Eeek! An error!", {"class" : "subtitle"}) + xhtml.para(text))


#
# This is highly dependent upon the layout in the include files, which
# makes this messy. XXX
#
def header(title, links):
  print
  print xhtml_init()
  
  print xhtml.title(title)
  print look_feel()

  print xhtml.link(None, {"rel" : "stylesheet", "href" : "/style/extended.css", "type" : "text/css", "media" : "screen", "title" : title})

  for href in links:
    print xhtml.link(None, {"rel" : "stylesheet", "href" : href, "type" : "text/css", "media" : "screen", "title" : title})
    pass

  print page_init()

  return (True)


def footer(prefix=None):
  if prefix != None:
    print prefix
    pass
  
  print page_fini()
  print xhtml_fini()
  
  #print xhtml.object("doesn't work", {"standby": "loading", "type" : "image/png",
  #"data" : 'data:base64, ' + xhtml.encodefile('/home/asdf/public_html/helvetix/anybrowser.png')})
  #                                      "data" : 'data:binary, ' + xhtml.rawfile('/home/asdf/public_html/helvetix/anybrowser.png')})

  return (True)


def displaycmd(cmd):
  fp = os.popen(cmd, "r")
  lines = fp.readlines()
  for l in lines:
    print '<pre style="color: grey;">' + l + '</pre>'
    pass
  fp.close()
  return


def xhtml_init():
  return (xhtml.include('%s/includes/wgo-xhtml-init.xhtml' % (config.DocumentRoot_path))
          + xhtml.comment("This document was automatically generated by wgo.py and friends."))


def xhtml_fini():
  return (xhtml.include('%s/includes/wgo-xhtml-fini.xhtml' % (config.DocumentRoot_path)))


def look_feel():
  # This is shared information with /includes/wgo-look-feel.xhtml XXX
  s = xhtml.include('%s/includes/wgo-layout.xhtml' % (config.DocumentRoot_path))
  s += xhtml.include('%s/includes/wgo-styles.xhtml' % (config.DocumentRoot_path))
  s += xhtml.include('%s/includes/wgo-navigation.xhtml' % (config.DocumentRoot_path))
  s += str(xhtml.link(None, {"rel" : "stylesheet", "href" : "/style/extended.css", "type" : "text/css", "media" : "screen"}))
  return (s)


def page_init(format="page"):
  return (xhtml.include(config.DocumentRoot_path + '/includes/wgo-' + format + '-init.xhtml'))


def page_fini(format="page"):
  return (xhtml.include(config.DocumentRoot_path + '/includes/wgo-' + format + '-fini.xhtml'))
