#!/usr/bin/env ${PYTHON}
# -*- mode: python py-indent-offset: 2; -*-
#
# www.gimp.org website administration and tools
#
# Copyright (C) 2002, 2003 Helvetix Victorinox, a pseudonym,
# Mountain View, California
# 
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
# USA

import xhtml
import wgo_config as config
import os

import apache_ssi


def spool_file(name, suffix=""):
  return (config.spool_dir + os.path.basename(name) + suffix)


def spool_path(name, suffix=""):
  return (config.spool_path + os.path.basename(name) + suffix)


def error(text):
  return (xhtml.div("Eeek! An error!", {"class" : "subtitle"}) + xhtml.para(text))


#
# This is highly dependent upon the layout in the include files, which
# makes this messy. XXX
#
def header(title, links):
  print
  print xhtml_init()
  
  print xhtml.title(title)
  print look_feel()

  print xhtml.link({"rel" : "stylesheet",
                    "href" : "/style/extended.css",
                    "type" : "text/css",
                    "media" : "screen",
                    "title" : title})

  for href in links:
    print xhtml.link({"rel" : "stylesheet",
                      "href" : href,
                      "type" : "text/css",
                      "media" : "screen",
                      "title" : title})
    pass
  
  print page_init()

  return (True)


def footer(prefix=None):
  if prefix != None:
    print prefix
    pass
  
  print page_fini()
  print xhtml_fini()
  
  #print xhtml.object("doesn't work", {"standby": "loading", "type" : "image/png",
  #"data" : 'data:base64, ' + xhtml.encodefile('/home/asdf/public_html/helvetix/anybrowser.png')})
  #                                      "data" : 'data:binary, ' + xhtml.rawfile('/home/asdf/public_html/helvetix/anybrowser.png')})

  return (True)


def displaycmd(cmd):
  fp = os.popen(cmd, "r")
  lines = fp.readlines()
  for l in lines:
    print '<pre style="color: grey;">' + l + '</pre>'
    pass
  fp.close()
  return


def xhtml_init():
  ssi = apache_ssi.processor()
  ssi.document_root = config.DocumentRoot_path
  s = ssi.parse(config.DocumentRoot_path + '/includes/wgo-xhtml-init.xhtml')
  s += xhtml.comment("This document was automatically generated by wgo.py $Revision$ and friends.")
  return (s)


def xhtml_fini():
  ssi = apache_ssi.processor()
  ssi.document_root = config.DocumentRoot_path
  s = ssi.parse(config.DocumentRoot_path + '/includes/wgo-xhtml-fini.xhtml')
  return (s)


def look_feel():
  ssi = apache_ssi.processor()
  ssi.document_root = config.DocumentRoot_path
  s = ssi.parse(config.DocumentRoot_path + '/includes/wgo-look-feel.xhtml')
  return (s)


def page_init(format="page"):
  ssi = apache_ssi.processor()
  ssi.document_root = config.DocumentRoot_path
  s = ssi.parse(config.DocumentRoot_path + '/includes/wgo-' + format + '-init.xhtml')
  return (s)


def page_fini(format="page"):
  ssi = apache_ssi.processor()
  ssi.document_root = config.DocumentRoot_path
  s = ssi.parse(config.DocumentRoot_path + '/includes/wgo-' + format + '-fini.xhtml')
  return (s)
